### ISSUE TITLE
[BUG] Distance functions and distance based classifiers bugs and features

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#596]
The distance based classifiers are not working properly, and there are several issues related to them. I am going to collate them here and comment on progress fixing them.

1. KNN with msm distance give exact same scores with different hyper-parameters
https://github.com/alan-turing-institute/sktime/issues/589

2. ColumnEnsembleClassifier fails fitting KNN classifiers
https://github.com/alan-turing-institute/sktime/issues/578

3. Cannot dump proximity forest model using joblib or pickle
https://github.com/alan-turing-institute/sktime/issues/600

4. AttributeError: 'ProximityStump' object has no attribute 'get_exemplars
https://github.com/alan-turing-institute/sktime/issues/598

More issues rolled into this one for clarity
5. Proximity Forest always using 2 processors #663
https://github.com/alan-turing-institute/sktime/issues/663

6. Derivative distance measures out
https://github.com/alan-turing-institute/sktime/issues/654

7. Distance measure unit testing
https://github.com/alan-turing-institute/sktime/issues/646

8. Variable length distance throws an error
https://github.com/alan-turing-institute/sktime/issues/645

9. Cross validation bug 
https://github.com/alan-turing-institute/sktime/issues/1057

10. Strange PF bug in orchestration
https://github.com/alan-turing-institute/sktime/issues/1114

There are several related issues which I am investigating, this is a work in progress. 

1. the sktime knn classifier has changed, and no longer has a _fit(X) method, so we use fir(X,y)
2. the DTW window sizes are, we think, not set correctly
3. there may be an issue with data transposition

actions are:
1. get the classifiers working
2. black box correctness vs tsml toolkit
3. write unit tests for distance functions and classifiers
4. make sure all tuning works correctly
5. fix the above issues

fixed 

KNeighboursTimeSeriesClassifier throws errors with multivariate time series data when algorithm is set to either 'kd_tree' or 'ball_tree
https://github.com/alan-turing-institute/sktime/issues/328
Euclidean distance for KNN
https://github.com/alan-turing-institute/sktime/issues/551

Bug with KNN
https://github.com/alan-turing-institute/sktime/issues/413

TypeError from KNeighborsTimeSeriesClassifier
https://github.com/alan-turing-institute/sktime/issues/608

**Comment by TonyBagnall** [comment]
PR https://github.com/alan-turing-institute/sktime/pull/579 changed _fit(X) to _fit(X,y) so that KNeighboursTimeSeriesClassifier actually runs.

**Comment by TonyBagnall** [comment]
update on this. @goastler has added a Euclidean distance function so Euclidean distance for KNN in PR #636 so issue
#551 should be fixed. We are currently assessing the structure of our distance functions to make them more sklearn compatible. Currently, series need to be transposed prior to the distance call. This is because vectorised operations require Fortran style matrices. However, it makes the distance functions unintuitive, and may be avoidable without the efficiency hit.

**Comment by TonyBagnall** [comment]
to do plan:
1) unit tests for all distance functions, sanity checked vs tsml implementations
2) test parameter setting for MSM to address #589 
3) test usage with cross validation
4) speed test vs other packages
5) address possible issues with PF

**Comment by AidenRushbrooke** [comment]
Regarding issue #413, I belive this is being caused by the cython distance function dtw_distance expecting the time series in the form (l,n), but currently they are being passed as (n,l), where l is the size of the time series and n is the number of dimensions. At least this is the case for the dataset used in the initial issue, and a few others I tested. This can be corrected using numpys transpose function, but I feel like the issue may be better solved in other ways.

**Comment by goastler** [comment]
I'll take (1) and (2) for this week. Hopefully fixing any discrepancies in the distance measures should solve (5) as well :)

**Comment by TonyBagnall** [comment]
#689 fixes some basic problems with time series knn, but it is not fully resolved. In particular, need to 
1. Verify other distances against tsml
2. recover distance parameters in the output file
3. debug parameter setting and tuning

**Comment by TonyBagnall** [comment]
transpose issue with KNN and EE resolved by PR #689 #697

Next up verification of 1-NN results vs tsml and introduce KNN unit tests

**Comment by mloning** [comment]
Once, achieving full API compliance is also related: https://github.com/alan-turing-institute/sktime/issues/257 (added KNN now)

**Comment by mloning** [comment]
Standardizing unit tests for classifiers would also be great, as you suggested, e.g. running all on ChinaTown and having reference results in a single table/dictionary.

**Comment by TonyBagnall** [comment]
standardising tests requires some thought as to the problem to use. If the test set is too big the distance based approaches take a long time, if its too small you may miss errors in the black box trest. How long is acceptable for testing all classifiers in this black box way do you think?

**Comment by mloning** [comment]
We could use different data sets for different classifiers if that would make things better. Would try to not make them much slower than they're currently are.

**Comment by TonyBagnall** [comment]
thats not the problem, we need to detect a delta in performance change. With KNN you can break it (e.g. only use first value) but still get a couple correct. More unit tests obviously means more testing time, and if we want to test the python versions it will take an age. I'll look at it next week

**Comment by TonyBagnall** [comment]
KNN unit testing now with euclidean,dtw, erp, wdtw, msm,and lcss now included with arrow head, will move when all the classifier unit tests are centralised. I have not done the derivative ones or mpdist as yet. Next up is checking knn with cross validation on the parameters, and to get the parameter info out into the results file @AidenRushbrooke can maybe do this

**Comment by mloning** [comment]
`classification/distance_based/tests/test_time_series_neighbors.py::test_knn_on_arrowhead` takes almost 4 mins to run. Any chance of speeding that up?

**Comment by TonyBagnall** [comment]
Going to revive this, and include the new distance functions in this issue

**Comment by TonyBagnall** [comment]
PF request 
https://github.com/alan-turing-institute/sktime/issues/388

**Comment by fkiraly** [comment]
also related to #1071, pairwise transformers include distances - please review :-)

**Comment by TonyBagnall** [comment]
right then, time to address these @chrisholder and @jasonlines

**Comment by TonyBagnall** [comment]
@chrisholder we can cross off the unit testing?

**Comment by TonyBagnall** [comment]
I think I will separate into issues with distances, KNN and ProximityForest

**Comment by TonyBagnall** [comment]
closed and split into three issues
